version: "3.7"
services:
  # Uncomment the following to serve the development webapp container (rebuilds on save).
  web:
    build:
      context: web
      dockerfile: Dockerfile.dev
    image: labflow/webapp-dev:latest
    tty: true
    environment:
      - "CHOKIDAR_USEPOLLING=true"
      - "REACT_APP_API_URL=${API_URL}"
      - "REACT_APP_AUTH_PROVIDER=${AUTH_PROVIDER}"
      - "REACT_APP_AUTH0_DOMAIN=${AUTH0_DOMAIN}"
      - "REACT_APP_AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}"
      - "REACT_APP_AUTH0_AUDIENCE=${AUTH0_API_AUDIENCE}"
    ports:
      - 3000:3000
    volumes:
      - ./web:/app
      - /app/node_modules
  # Uncomment the following to serve the production webapp container.
  # webapp:
  #   build: web
  #   image: labflow/webapp:latest
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - "REACT_APP_API_URL=${API_URL}"
  #     - "REACT_APP_AUTH_PROVIDER=${AUTH_PROVIDER}"
  #     - "REACT_APP_AUTH0_DOMAIN=${AUTH0_DOMAIN}"
  #     - "REACT_APP_AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}"
  #     - "REACT_APP_AUTH0_AUDIENCE=${AUTH0_API_AUDIENCE}"
  server:
    build: server
    image: labflow/server:latest
    environment:
      - FLASK_ENV=development
      - PORT=5000
      - PROPAGATE_EXCEPTIONS=True
      - "SERVER_NAME=${SERVER_NAME}"
      - "SQLALCHEMY_DATABASE_URI=postgresql+pg8000://postgres:${POSTGRES_PASSWORD}@db/labflow"
      - "AUTH_PROVIDER=${AUTH_PROVIDER}"
      - "AUTH0_DOMAIN=${AUTH0_DOMAIN}"
      - "AUTH0_API_AUDIENCE=${AUTH0_API_AUDIENCE}"
      - "AUTH0_AUTHORIZATION_URL=${AUTH0_AUTHORIZATION_URL}"
      - "AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}"
      - "AUTH0_TOKEN_URL=${AUTH0_TOKEN_URL}"
    ports:
      - 5000:5000
    volumes:
      - ./server:/app
  db:
    image: supabase/postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: labflow
    volumes:
      - ./.postgres:/var/lib/postgresql/data